#"""
#****************************************
# * @author: Chandler Qian
# * Date: 3/11/21
# * Project: the project this script belongs to
# * Purpose: configuration file for all the tables, and parameters
# * Project root: /home/usr/projects/safety-recommendation
#****************************************
#"""

# Directory
directory:
  safety_clu: './safety_cluster/'